
prueba:
  propiedad: "Hola mundo nueva props dfsdfdsf aaaaaaaaaaaaaaa bbbbb cccccccc ddd"

spring:
  data:
    mongodb:
      uri: mongodb+srv://johan:123@cluster0.gyhh4kw.mongodb.net/productdb?retryWrites=true&w=majority